### PR TITLE
Renders news based on current sport selected

### PR DESCRIPTION
**Pull request by aileen-ji**
- Added onClick events for the side navbar to set the currentSport based on selection
- Created Home context to fetch news using axios
- Styled the news section to display two most recent news articles about the currentSport

### CODE REVIEW

**Review by Rebecca-CYLi — APPROVED** [review]
a lot of edits + new component, g2g
next time, make sure to add the PR reviewers in the right side panel as well

**Review by LifeBringer — COMMENTED** [review]
Needs more comments @Rebecca-CYLi

**Comment by LifeBringer** [comment]
Not in the CSS but the component changes

**Comment by Rebecca-CYLi** [comment]
gotcha, will be sure to keep that in mind for future PRs @LifeBringer

**Pull request merged**
